export const CartActionTypes = {
  SET_HIDDEN: "[CART] SET HIDDEN",
  TOGGLE_HIDDEN: "[CART] TOGGLE HIDDEN",
  ADD_CART_ITEM: "[CART] ADD CART ITEM",
  DELETE_CART_ITEM: "[CART] DELETE CART ITEM",
  DECREASE_CART_ITEM: "[CART] DECREASE CART ITEM",
};
