const ShopActionTypes = {
  FETCH_COLLECTIONS_START: '[SHOP] FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_SUCCESS: '[SHOP] FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_FAILURE: '[SHOP] FETCH_COLLECTIONS_FAILURE',
  FETCH_COLLECTIONS: '[SHOP] FETCH_COLLECTIONS',
}

export default ShopActionTypes
