const UserActionTypes = {
  SET_CURRENT_USER: '[USER] SET CURRENT USER',
  GOOGLE_SIGN_IN_START: '[USER] GOOGLE SIGN IN START',
  EMAIL_SIGN_IN_START: '[USER] EMAIL SIGN IN START',
  SIGN_IN_SUCCESS: '[USER] SIGN IN SUCCESS',
  SIGN_IN_FAILURE: '[USER] SIGN IN FAILURE',
  CHECK_USER_SESSION: '[USER] CHECK USER SESSION',
  SIGN_OUT_START: '[USER] SIGN OUT START',
  SIGN_OUT_SUCCESS: '[USER] SIGN OUT SUCCESS',
  SIGN_OUT_FAILURE: '[USER] SIGN OUT FAILURE',
}
export default UserActionTypes
