const UserActionTypes = {
  SET_CURRENT_USER: '[USER] SET CURRENT USER',
  CHECK_USER_SESSION: '[USER] CHECK USER SESSION',

  GOOGLE_SIGN_IN_START: '[USER] GOOGLE SIGN IN START',
  EMAIL_SIGN_IN_START: '[USER] EMAIL SIGN IN START',
  SIGN_IN_SUCCESS: '[USER] SIGN IN SUCCESS',
  SIGN_IN_FAILURE: '[USER] SIGN IN FAILURE',

  SIGN_OUT_START: '[USER] SIGN OUT START',
  SIGN_OUT_SUCCESS: '[USER] SIGN OUT SUCCESS',
  SIGN_OUT_FAILURE: '[USER] SIGN OUT FAILURE',

  SIGN_UP_START: '[USER] SIGN UP START',
  SIGN_UP_SUCCESS: '[USER] SIGN UP SUCCESS',
  SIGN_UP_FAILURE: '[USER] SIGN UP FAILURE',
}
export default UserActionTypes
